version: "3.9"

services:
  web:
    build: .
    container_name: gestion_stages_web
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY:-django-insecure-change-me}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-127.0.0.1,localhost}
      EMAIL_BACKEND: ${EMAIL_BACKEND:-django.core.mail.backends.console.EmailBackend}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL:-noreply@gestion-stages.local}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
