# Generated by Django 6.0.3 on 2026-05-12 15:10

import stages.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', stages.models.UserManager()),
            ],
        ),
    ]
